### ISSUE TITLE
11.5.1 and OC 0.7.3 support

### ISSUE THREAD

**Issue by benji1703** [bangbaew/Gigabyte-B460M-DS3H-Hackintosh#13]
Hi!
Do you plan to upgrade to OC 0.7.3 and latest Big Sur?
I am failing to install using latest version, stuck on apple logo and directly back to bios…

**Comment by bangbaew** [comment]
I couldn't boot with OC 0.7.3 as well, but my macOS version is 11.5.2 and it works fine with 0.7.2,
so I think I'll continue using OC 0.7.2 until there's a solution to the problem.

**Comment by bangbaew** [comment]
Have you fixed the problem yet? I've upgraded to 0.7.4
the problem is that they changed how drivers are loaded in the config.plist, so OC 0.7.3 won't be able to load drivers from 0.7.2 config.plist
(https://www.reddit.com/r/hackintosh/comments/pk641k/for_anyone_stuck_after_upgrade_to_oc_073/)

So, you can just update to the latest OC Configurator, open your config.plist and save it again, it will optimize for the release version of OC Configurator, you can check if your config.plist works with the latest OC version with OC config validator (https://github.com/chris1111/Config-Validator)
