### ISSUE TITLE
Works without the RX480?

### ISSUE THREAD

**Issue by vnevarezt** [bangbaew/Gigabyte-B460M-DS3H-Hackintosh#9]
Hello I am new to this, before buying the components I would like to know if the EFI file will be compatible with my pc with the same components even though I do not have the RX480, at the moment I do not want to buy it and I want to know if not having this It can cause some compatibility problem maybe losing functions, if someone can inform me about it I would appreciate it

**Comment by bangbaew** [comment]
It depends on your GPU, if you have another natively supported GPU such as GTX 770 or RX 580, it would be fine.
But if you don't have any  external GPU, you'll have you change the SMBIOS and do some framebuffer patching so Intel iGPU will work. This EFI contains SSDT patch for CPU and MB, but no iGPU.

**Comment by okimangelo** [comment]
I used this one because I am using the same motherboard. Just use GenSMBIOS
to generate your config file. I am using Radeon RX5500XT (gigabyte) and I
needed to use Macpro 1,1 config.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
